name: CI

# triggers upon push/pull request for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('requirements/linux-64.txt') }}

      - name: Write the secrets.json file 
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/secrets.json
          encodedString: ${{ secrets.SECRETS_BASE64_FILE }}

      - name: Set up Conda and activate virtual environment
        uses: conda-incubator/setup-miniconda@v1
        with: 
          auto-update-conda: true
          activate-environment: poandy
          python-version: 3.8.5
          channels: conda-forge, defaults
          channel-priority: true
          environment-file: requirements/linux-64.txt
          use-only-tar-bz2: true

      - name: Ensure code has been formatted with Black
        run: conda run -n poandy python -m black . --check

      - name: Run automated tests with PyTest
        run: conda run -n poandy python -m pytest